### ISSUE TITLE
Сделать что бы кнопка позвонить работала на телефоне

### ISSUE THREAD

**Issue by pavliha** [pavliha/partymaker-web#41]
![image](https://user-images.githubusercontent.com/10353006/68527845-3dc7c700-02f4-11ea-8482-5c5f4cd9c67f.png)
для дектопа показывать сбоку номер

**Comment by LexaLukovka** [comment]
Сделал. Нужно протестить на телефоне

**Comment by LexaLukovka** [comment]
На вебе открывает скайп для бизнеса - это значит все работает

**Comment by pavliha** [comment]
2h
