### ISSUE TITLE
Добавить кнопку поделится

### ISSUE THREAD

**Issue by pavliha** [pavliha/partymaker-web#42]
![image](https://user-images.githubusercontent.com/10353006/68527886-d2cac000-02f4-11ea-8d35-1aa147972810.png)

**Comment by LexaLukovka** [comment]
web share api

**Comment by LexaLukovka** [comment]
Реализовал по функционалу, но еще есть проблемы с url. Не хочет отсылать ссылкой. 
In progress

**Comment by pavliha** [comment]
3h
